create extension if not exists pgcrypto;
create schema if not exists identity; create schema if not exists platform; create schema if not exists audit; create schema if not exists async; create schema if not exists files;

create table identity.account(id uuid primary key default gen_random_uuid(),email varchar(254) not null unique,display_name varchar(160) not null,password_hash varchar(100) not null,role varchar(50) not null,enabled boolean not null default true,created_at timestamptz not null default now());
create table identity.mfa_challenge(id uuid primary key,account_id uuid not null references identity.account(id),expires_at timestamptz not null,used_at timestamptz);
create table identity.session(id uuid primary key,account_id uuid not null references identity.account(id),token_hash char(64) not null unique,expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null default now());
create index session_active_idx on identity.session(token_hash,expires_at) where revoked_at is null;
create table identity.role_summary(id uuid primary key default gen_random_uuid(),name varchar(100) not null unique,user_count int not null,policy_count int not null,scope varchar(120) not null);

create table platform.module(id uuid primary key default gen_random_uuid(),name varchar(120) not null,module_key varchar(80) not null unique,version varchar(30) not null,status varchar(30) not null,description varchar(240) not null,metric varchar(80) not null,sort_order int not null);
create table platform.resource_descriptor(id uuid primary key default gen_random_uuid(),name varchar(160) not null,storage_mode varchar(20) not null check(storage_mode in('DOMAIN','DYNAMIC')),owner_module varchar(80) not null,record_count bigint not null default 0,schema_version varchar(20) not null,updated_at timestamptz not null default now());
create table platform.activity(id uuid primary key default gen_random_uuid(),kind varchar(20) not null,name varchar(180) not null,metadata varchar(240) not null,status varchar(30) not null,occurred_at timestamptz not null default now());
create table audit.event(id uuid primary key,actor_id uuid,actor_email varchar(254),action varchar(100) not null,result varchar(30) not null,correlation_id uuid default gen_random_uuid(),occurred_at timestamptz not null);
create table async.outbox_event(id uuid primary key default gen_random_uuid(),event_type varchar(180) not null,payload jsonb not null default '{}',status varchar(20) not null default 'PENDING',attempts int not null default 0,available_at timestamptz not null default now(),created_at timestamptz not null default now());
create table async.job(id uuid primary key default gen_random_uuid(),job_type varchar(120) not null,status varchar(20) not null,payload jsonb not null default '{}',attempts int not null default 0,max_attempts int not null default 3,created_at timestamptz not null default now());
create table files.file_object(id uuid primary key default gen_random_uuid(),name varchar(255) not null,media_type varchar(120) not null,size_bytes bigint not null check(size_bytes>=0),classification varchar(30) not null,status varchar(30) not null,checksum_sha256 char(64) not null,updated_at timestamptz not null default now());

-- BCrypt hash for demo password Core@2026
insert into identity.account(email,display_name,password_hash,role) values('admin@core.local','Minh Nguyễn','$2a$12$m9QvIHzKvI3NEc.E4IhNWuFd8hoARwdzkGaGpTA7rUlYxkYQ6KrrK','PLATFORM_ADMIN');
insert into identity.role_summary(name,user_count,policy_count,scope) values ('Platform Administrator',3,12,'Toàn deployment'),('Module Maintainer',8,7,'Theo module'),('Security Auditor',2,5,'Chỉ đọc + export'),('Application User',184,9,'Theo organization');
insert into platform.module(name,module_key,version,status,description,metric,sort_order) values
('Local Identity','local-identity','1.0.0','HEALTHY','Tài khoản, phiên đăng nhập và MFA','4 contracts',1),('Permission','permission','1.0.0','HEALTHY','Policy, vai trò và record scope','6 policies',2),('Audit Store','audit-store','1.0.0','HEALTHY','Audit append-only và checkpoint','12.4k records',3),('Event Outbox','event-outbox','1.0.0','ATTENTION','Outbox, inbox và delivery relay','12 pending',4),('Job Queue','job-queue','1.0.0','HEALTHY','Job, scheduler và retry','3 running',5),('File Management','file-management','1.0.0','HEALTHY','Upload, scan và object storage','84.2 GB',6),('Dynamic Resource','dynamic-resource','1.0.0','HEALTHY','Definition, generic API và history','24 definitions',7),('Webhook','webhook','1.0.0','DISABLED','Delivery tới hệ thống bên ngoài','Optional',8);
insert into platform.resource_descriptor(name,storage_mode,owner_module,record_count,schema_version,updated_at) values ('Approval Request','DOMAIN','sample-domain',1248,'v3',now()-interval '2 minutes'),('Customer Preference','DYNAMIC','dynamic-resource',8492,'v2',now()-interval '8 minutes'),('Service Account','DOMAIN','local-identity',42,'v1',now()-interval '34 minutes'),('Notification Template','DYNAMIC','notification',86,'v4',now()-interval '1 hour'),('File Object','DOMAIN','file-management',24903,'v2',now()-interval '2 hours');
insert into platform.activity(kind,name,metadata,status,occurred_at) values ('EVENT','approval-request.approved.v1','sample-domain · tenant acme-vn','PUBLISHED',now()-interval '2 minutes'),('JOB','file.reconcile','attempt 1/3','RUNNING',now()-interval '3 minutes'),('EVENT','identity.session-revoked.v1','local-identity · security','PUBLISHED',now()-interval '5 minutes'),('JOB','audit.checkpoint','12,400 events','SUCCEEDED',now()-interval '9 minutes');
insert into async.outbox_event(event_type) select 'demo.pending.v1' from generate_series(1,12); insert into async.job(job_type,status) select 'demo.worker','RUNNING' from generate_series(1,3);
insert into files.file_object(name,media_type,size_bytes,classification,status,checksum_sha256,updated_at) values ('architecture-standard-v1.1.pdf','application/pdf',2516582,'INTERNAL','ACTIVE',repeat('a',64),now()),('customer-import-2026-08.csv','text/csv',19608371,'CONFIDENTIAL','ACTIVE',repeat('b',64),now()-interval '1 day'),('audit-checkpoint-20260814.sig','application/octet-stream',4096,'RESTRICTED','ACTIVE',repeat('c',64),now()-interval '1 day'),('module-manifest.yaml','text/yaml',12288,'INTERNAL','QUARANTINE',repeat('d',64),now()-interval '3 days');
